**ht-1 = tanh( Wh·ht-2 + Wx·"Movies" + b )**

**ht = tanh( Wh·ht-1 + Wx·"was" + b )**

**ht+1 = tanh( Wh·ht + Wx·"Good" + b )**

**ht+1 = tanh( Wh·(tanh( Wh·(tanh( Wh·ht-2 + Wx·"Movies" + b )) + Wx·"was" + b )) + Wx·"Good" + b )**

In [14]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding

In [22]:
train_sentences = [
    'The movie was truly amazing',      # Positive (1)
    'I absolutely loved the pizza',     # Positive (1)
    'The service was terrible',         # Negative (0)
    'I really hated the boring movie'   # Negative (0)
]
labels = np.array([1, 1, 0, 0])

In [23]:
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(train_sentences)
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'movie': 3,
 'was': 4,
 'i': 5,
 'truly': 6,
 'amazing': 7,
 'absolutely': 8,
 'loved': 9,
 'pizza': 10,
 'service': 11,
 'terrible': 12,
 'really': 13,
 'hated': 14,
 'boring': 15}

In [24]:
sequences = tokenizer.texts_to_sequences(train_sentences)
print(sequences)

[[2, 3, 4, 6, 7], [5, 8, 9, 2, 10], [2, 11, 4, 12], [5, 13, 14, 2, 15, 3]]


In [25]:
padded_data = pad_sequences(sequences, maxlen=8, padding='post')
padded_data = np.array(padded_data)
print(padded_data)

[[ 2  3  4  6  7  0  0  0]
 [ 5  8  9  2 10  0  0  0]
 [ 2 11  4 12  0  0  0  0]
 [ 5 13 14  2 15  3  0  0]]


In [26]:
# 3. THE MODEL (Sequential)
model = Sequential()

# Layer 1: Embedding (The DNA Learner) - Converts numbers to meaning
model.add(Embedding(input_dim=100, output_dim=8))

# Layer 2: SimpleRNN (The Sequence Reader) - Reads step-by-step
model.add(SimpleRNN(16))

# Layer 3: Output (The Decision) - 0 to 1 Score
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
# 4. TRAIN (Teach the brain)
model.fit(padded_data, labels, epochs=50)

# 5. PREDICT (Test it!)
test_text = ["movie was good"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq, maxlen=8)

preds = model.predict(test_pad)
print("Prediction:", preds)  # Output: [[0.92]] (Positive!)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step - accuracy: 1.0000 - loss: 0.1899
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - accuracy: 1.0000 - loss: 0.1788
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.1686
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.1591
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.1504
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.1424
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.1350
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.1283
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.1220
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 1.0000 - loss: 0.1163
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.1110
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.106